export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_COMMANDES_REQUEST = 'GET_COMMANDES_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';